import Head from 'next/head'
import { Inter } from 'next/font/google'
import { createClient } from "next-sanity";


const inter = Inter({ subsets: ['latin'] })

const query = `*[_type == "product"]`;

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          Home
          <ul>
            {products.map((product) => (
              <li key={product._id}>{product.product_name}</li>
            ))}
          </ul>
        </div>
      </main>

    </>
  )
};

const client = createClient({
  projectId: "pm9q8702",
  dataset: "production",
  useCdn: true, 
  token: process.env.NEXT_PUBLIC_SANITY_KEY,
});

export async function getStaticProps() {
  const products = await client.fetch(query);
  return {
    props: {
      products
    }
  };
}
