import Head from 'next/head'
import { client, urlFor } from '../lib/sanity'
import Image from 'next/image';




export default function Home({ products, firstImage }) {
  return (
    <>
      <Head>
        <title>Wicked Prints</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <image src={urlFor(firstImage.image).url()} alt='' />

    </>
  )
};

export async function getStaticProps() {
  const query = `*[_type == "product"]`;
  const products = await client.fetch(query);

  const bannerQuery = `*[_type == "banner"]`;
  const bannerData = await client.fetch(bannerQuery);
  const firstImage = await bannerData[0]
  console.log(firstImage);
  console.log(urlFor(firstImage.image).url());
  return {
    props: {
      products, 
      firstImage
    }
  };
}
